// <auto-generated />
using System;
using System.Collections.Generic;
using FinanceTracker.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceTracker.Core.Migrations
{
    [DbContext(typeof(FinanceTrackerContext))]
    [Migration("20250811113859_AddedPhysicalAllocation")]
    partial class AddedPhysicalAllocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("FinanceTracker.Core.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FinanceTracker.Core.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.HasIndex("Id", "Name")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("FinanceTracker.Core.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("FinanceTracker.Core.HistoricValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DebtId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PhysicalAllocationId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Value", "FinanceTracker.Core.HistoricValue.Value#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("AmountInMainCurrency")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("DebtId");

                    b.HasIndex("PhysicalAllocationId");

                    b.ToTable("HistoricValues");
                });

            modelBuilder.Entity("FinanceTracker.Core.InflationHistoricValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("InflationValues");
                });

            modelBuilder.Entity("FinanceTracker.Core.PhysicalAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PhysicalAllocation");
                });

            modelBuilder.Entity("FinanceTracker.Core.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("FinanceTracker.Core.WalletTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValueInMainCurrency")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTargets");
                });

            modelBuilder.Entity("FinanceTracker.Core.Component", b =>
                {
                    b.HasOne("FinanceTracker.Core.Wallet", null)
                        .WithMany("Components")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceTracker.Core.HistoricValue", b =>
                {
                    b.HasOne("FinanceTracker.Core.Asset", null)
                        .WithMany("ValueHistory")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinanceTracker.Core.Component", null)
                        .WithMany("ValueHistory")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinanceTracker.Core.Debt", null)
                        .WithMany("ValueHistory")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinanceTracker.Core.PhysicalAllocation", null)
                        .WithMany("ValueHistory")
                        .HasForeignKey("PhysicalAllocationId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FinanceTracker.Core.WalletTarget", b =>
                {
                    b.HasOne("FinanceTracker.Core.Wallet", null)
                        .WithMany("Targets")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinanceTracker.Core.Asset", b =>
                {
                    b.Navigation("ValueHistory");
                });

            modelBuilder.Entity("FinanceTracker.Core.Component", b =>
                {
                    b.Navigation("ValueHistory");
                });

            modelBuilder.Entity("FinanceTracker.Core.Debt", b =>
                {
                    b.Navigation("ValueHistory");
                });

            modelBuilder.Entity("FinanceTracker.Core.PhysicalAllocation", b =>
                {
                    b.Navigation("ValueHistory");
                });

            modelBuilder.Entity("FinanceTracker.Core.Wallet", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
