// <auto-generated />
using System;
using System.Collections.Generic;
using FinanceTracker.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceTracker.Core.Migrations
{
    [DbContext(typeof(FinanceTrackerContext))]
    [Migration("20250921144440_DroppedOldEntities")]
    partial class DroppedOldEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("FinanceTracker.Core.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultPhysicalAllocationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultPhysicalAllocationId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Id", "Name")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GroupTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.GroupType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GroupTypes");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.HistoricTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValueInMainCurrency")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("WalletTargets");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.HistoricValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PhysicalAllocationId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Value", "FinanceTracker.Core.Entities.HistoricValue.Value#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("AmountInMainCurrency")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("PhysicalAllocationId");

                    b.ToTable("HistoricValues");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.InflationHistoricValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("InflationValues");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.PhysicalAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplaySequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PhysicalAllocations");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.Component", b =>
                {
                    b.HasOne("FinanceTracker.Core.Entities.PhysicalAllocation", null)
                        .WithMany()
                        .HasForeignKey("DefaultPhysicalAllocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinanceTracker.Core.Entities.Group", "Group")
                        .WithMany("Components")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.Group", b =>
                {
                    b.HasOne("FinanceTracker.Core.Entities.GroupType", "GroupType")
                        .WithMany("Groups")
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupType");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.HistoricTarget", b =>
                {
                    b.HasOne("FinanceTracker.Core.Entities.Group", null)
                        .WithMany("Targets")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.HistoricValue", b =>
                {
                    b.HasOne("FinanceTracker.Core.Entities.Component", "Component")
                        .WithMany("ValueHistory")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinanceTracker.Core.Entities.PhysicalAllocation", null)
                        .WithMany("ValueHistory")
                        .HasForeignKey("PhysicalAllocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Component");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.Component", b =>
                {
                    b.Navigation("ValueHistory");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.Group", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.GroupType", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("FinanceTracker.Core.Entities.PhysicalAllocation", b =>
                {
                    b.Navigation("ValueHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
