// <auto-generated />
using System;
using System.Collections.Generic;
using FinanceTracker.Web;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceTracker.Web.Migrations
{
    [DbContext(typeof(FinanceTrackerContext))]
    partial class FinanceTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("FinanceTracker.Core.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FinancedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FinancedById");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("FinanceTracker.Core.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("FinanceTracker.Core.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("FinanceTracker.Core.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("FinanceTracker.Core.Primitives.HistoricValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DebtId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Value", "FinanceTracker.Core.Primitives.HistoricValue.Value#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("AmountInMainCurrency")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("DebtId");

                    b.ToTable("HistoricValues");
                });

            modelBuilder.Entity("FinanceTracker.Core.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Target")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("FinanceTracker.Core.Asset", b =>
                {
                    b.HasOne("FinanceTracker.Core.Debt", "FinancedBy")
                        .WithMany()
                        .HasForeignKey("FinancedById");

                    b.HasOne("FinanceTracker.Core.Portfolio", null)
                        .WithMany("Assets")
                        .HasForeignKey("PortfolioId");

                    b.Navigation("FinancedBy");
                });

            modelBuilder.Entity("FinanceTracker.Core.Component", b =>
                {
                    b.HasOne("FinanceTracker.Core.Wallet", null)
                        .WithMany("Components")
                        .HasForeignKey("WalletId");
                });

            modelBuilder.Entity("FinanceTracker.Core.Debt", b =>
                {
                    b.HasOne("FinanceTracker.Core.Portfolio", null)
                        .WithMany("Debts")
                        .HasForeignKey("PortfolioId");
                });

            modelBuilder.Entity("FinanceTracker.Core.Primitives.HistoricValue", b =>
                {
                    b.HasOne("FinanceTracker.Core.Asset", null)
                        .WithMany("ValueHistory")
                        .HasForeignKey("AssetId");

                    b.HasOne("FinanceTracker.Core.Component", null)
                        .WithMany("ValueHistory")
                        .HasForeignKey("ComponentId");

                    b.HasOne("FinanceTracker.Core.Debt", null)
                        .WithMany("AmountHistory")
                        .HasForeignKey("DebtId");
                });

            modelBuilder.Entity("FinanceTracker.Core.Wallet", b =>
                {
                    b.HasOne("FinanceTracker.Core.Portfolio", null)
                        .WithMany("Wallets")
                        .HasForeignKey("PortfolioId");
                });

            modelBuilder.Entity("FinanceTracker.Core.Asset", b =>
                {
                    b.Navigation("ValueHistory");
                });

            modelBuilder.Entity("FinanceTracker.Core.Component", b =>
                {
                    b.Navigation("ValueHistory");
                });

            modelBuilder.Entity("FinanceTracker.Core.Debt", b =>
                {
                    b.Navigation("AmountHistory");
                });

            modelBuilder.Entity("FinanceTracker.Core.Portfolio", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Debts");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("FinanceTracker.Core.Wallet", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
